name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Setup Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '16'

      - name: Convert README to HTML
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>README</title></head><body>' > index.html
          cat README.md | markdown >> index.html
          echo '</body></html>' >> index.html

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: index.html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
